create a google benchmark with chaos-mesh
camunda-community-hub/camunda-8-helm-profiles pull request #43
Opened 2022-11-11 15:16 UTC by chDame

2022-11-18 11:00 UTC, chDame commented on benchmark/Makefile
> +export chartValues ?= "$(root)/benchmark/camunda-values-benchmark.yaml"
done

2022-11-18 11:00 UTC, chDame commented on benchmark/Makefile
> +	pkill -f "port-forward"
done

2022-11-18 11:00 UTC, chDame commented on benchmark/benchmark.yaml
> +        image: gcr.io/camunda-researchanddevelopment/falko-camunda-8-benchmark:0.0.1-SNAPSHOT
done

2022-11-18 11:01 UTC, chDame commented on benchmark/camunda-values-benchmark.yaml
> +      value: "true"
done

2022-11-18 11:01 UTC, chDame commented on benchmark/camunda-values-benchmark.yaml
> +  ioThreadCount: 15
done

2022-11-24 14:47 UTC, falko requested changes
Submodule chaos-mesh should be removed

2022-11-24 14:47 UTC, falko commented on benchmark/chaosmesh.mk
> +	-kubectl delete -f network-chaos.yaml -n default
to be deleted

2022-11-24 14:47 UTC, falko commented on google/benchmark/README.md
> +# Camunda 8 Helm Profile: Ingress NGINX for GCP with TLS Certificates
Let's update the title

2022-11-24 14:47 UTC, falko commented on google/benchmark/README.md
> +5. The ingress controller is annotated so that letsencrypt tls certificates are provisioned.
either delete or describe what the makefile does

2023-01-09 13:52 UTC, falko commented
What is missing to get this merged?

2023-01-13 16:18 UTC, upgradingdave commented
Hi @falko, @chDame, I glanced thru the changes and I also read @falko's comments and I think all that is remaining before we can merge is to:

- [ ]  refactor the chaos mesh related files into a separate `chaos-mesh` directory
- [ ] Update `google/benchmark/README` with a few small changes to make things more clear
- [ ] Add a `README.md` to the `benchmark` directory

I can possibly work on these this afternoon and over the weekend, let me know if you can think of anything else to clean up before merging?

2023-01-13 17:02 UTC, falko commented
I have some improvements in Zeebe Tuner that might be worth merging back to the Helm Profiles. In general, I'd like to get Zeebe Tuner use the profiles as much as possible so that we don't have to maintain two benchmark profiles in the end. I could look into that on Monday

2023-01-20 15:01 UTC, falko commented
> Hi @falko, @chDame, I glanced thru the changes and I also read @falko's comments and I think all that is remaining before we can merge is to:
> 
> * [ ]   refactor the chaos mesh related files into a separate `chaos-mesh` directory
> * [ ]  Update `google/benchmark/README` with a few small changes to make things more clear
> * [ ]  Add a `README.md` to the `benchmark` directory
> 
> I can possibly work on these this afternoon and over the weekend, let me know if you can think of anything else to clean up before merging?

@upgradingdave feel free to contribute all these things to the main branch. @chDame and I will merge the PR now.

2023-01-20 15:01 UTC, falko approved these changes

2023-01-20 15:02 UTC, merged